### ISSUE TITLE
Should BLOCKY here be m2 instead?

### ISSUE THREAD

**Issue by aaronma37** [orzzzjq/Parallel-Banding-Algorithm-plus#6]
https://github.com/orzzzjq/Parallel-Banding-Algorithm-plus/blob/2f58720302c3478d4367b21268dfbb263b46c4d2/pba-plus-3D/pba/pba3DHost.cu#L105

Same for BLOCKY in m1 in the function above.  In the 2D version, this is the case.  

Does the current code imply phase 1 band = 4, phase 2 band =4, and phase 3 band =2?

**Comment by orzzzjq** [comment]
For 3D distance transform, the banding method is not useful as there is already enough computation. Currently ```m1=m2=1, m3=2```. You can see https://www.comp.nus.edu.sg/~tants/pba.html for more info.
