### ISSUE TITLE
The result for the first row is incorrect

### ISSUE THREAD

**Issue by y123l** [orzzzjq/Parallel-Banding-Algorithm-plus#7]
The size of the sample image is 64 x 64, and the pixel is set as follows:
    for(int i=0; i<pixels; i++) {
        if(i%7)
            pSrcHost[i] = 0x01;
        else
            pSrcHost[i] = 0x00;
    }

![image](https://github.com/orzzzjq/Parallel-Banding-Algorithm-plus/assets/50011027/6c095ced-4228-4725-899e-03665c503036)

**Comment by y123l** [comment]
Continue with the previous comment,  pixel with value of 0 is set to site. The left side of the image is the correct result of Voronoi, and the right side is the result of PBA. The data stored is of the short type, for example, count from 0, the 3th pixel' correct Voronoi data is (5, 2) [The square of Euclidean distance is 8], but the PBA result is (0, 0)  [The square of Euclidean distance is 9]. So, what is the cause of this error. Looking forward to your reply, thanks!

**Comment by orzzzjq** [comment]
Cannot really understand the picture. The size 64 x 64 is probably too small for PBA. Could you let me know the parameters you used:
https://github.com/orzzzjq/Parallel-Banding-Algorithm-plus/blob/2f58720302c3478d4367b21268dfbb263b46c4d2/pba-plus-2D/main.cpp#L49-L55

**Comment by y123l** [comment]
Thanks! The above problem was solved, but I ran into a new problem, when I set the width and height to 2048,  phase1Band = phase2Band  = 32, phase3Band  = 2. The program is stuck in an infinite loop  in function 'kernelColor'
`            while (last2.y >= 0) {
                dx = last1.x - tx; dy = last2.y - ty; 
                dist = __mul24(dx, dx) + __mul24(dy, dy); 

                if (dist > best) 
                    break; 

                best = dist; lasty = last2.y; last2 = last1;

                if (last2.y >= 0) 
                    last1 = input[TOID(tx, last2.y, size)];
            }`

**Comment by orzzzjq** [comment]
2048 is the default example, which should provide a correct answer. Please let me know how you initialize your input
https://github.com/orzzzjq/Parallel-Banding-Algorithm-plus/blob/2f58720302c3478d4367b21268dfbb263b46c4d2/pba-plus-2D/main.cpp#L103-L104

**Comment by y123l** [comment]
template <typename T>
void transform2Dtexture(T *pSrc, int nSrcStep, T nMinSiteValue, T nMaxSiteValue, short2 *input, int width, int height, cudaStream_t stream) {
    dim3 blockSize(16, 16);
    dim3 gridSize((width + blockSize.x - 1) / blockSize.x, 
                  (height + blockSize.y - 1) / blockSize.y);

    transformKernel<<<gridSize, blockSize, 0, stream>>>(pSrc, nSrcStep, nMinSiteValue, nMaxSiteValue, input, width, height);
}

template <typename T>
__global__ void transformKernel(T *pSrc, int nSrcStep, T nMinSiteValue, T nMaxSiteValue, 
                                short2 *input, int width, int height) {
    int x = blockIdx.x * blockDim.x + threadIdx.x;
    int y = blockIdx.y * blockDim.y + threadIdx.y;

    if (x < width && y < height) {
        T value = pSrc[y * nSrcStep + x];
        short2 markerPair = make_short2(MARKER, MARKER);

        if (value >= nMinSiteValue && value <= nMaxSiteValue) {
            input[y * width + x] = make_short2(x, y);
        } else {
            input[y * width + x] = markerPair;
        }
    }
}

**Comment by y123l** [comment]
Be more specific , the program will stuck in an infinite loop with width >= 256 and it will perform normally with width <=128.  (phase1Band  = phase2Band = width/64;  phase3Band = 2)

**Comment by orzzzjq** [comment]
Can you try to initialize your input with CPU to see if there is something wrong with the input? It is difficult for me to understand the code without any comments.

**Comment by y123l** [comment]
solved! many thanks!

**Comment by orzzzjq** [comment]
Welcome :)
